### ISSUE TITLE
Enable regex pattern on application.json "state" property

### ISSUE THREAD

**Issue by ravpacheco** [takenet/blip-sdk-csharp#4]
Sometimes, can be useful use a regex pattern on application.json "state" property.

Imagine the scenario:

* Your flow has 2 states: **3.1.1** and **3.1.2**
* For the both states you want process the user input on **TextMessageReceiver**

Today you must create two differents receivers settings like:

```
{
      "type": "TextMessageReceiver",
      "mediaType": "text/plain",
      "state": "3.1.1"
},
{
      "type": "TextMessageReceiver",
      "mediaType": "text/plain",
      "state": "3.1.2"
}
```

Using a regex pattern you can just do:

```
{
      "type": "TextMessageReceiver",
      "mediaType": "text/plain",
      "state": "^3.1.(1|2)?"
}
```

**Comment by ceifa** [comment]
Perhaps a flag property should be added to tell if this is a regex or not. This would prevent some receivers from being called improperly, for example in a scenario where one state is called `1.1` and another is called `1.1.2`. Something like:


```
{
      "type": "TextMessageReceiver",
      "mediaType": "text/plain",
      "state": "^3.1.(1|2)?",
      "stateResolver": "regex"
}
```

**Comment by andreminelli** [comment]
> 
> 
> Perhaps a flag property should be added to tell if this is a regex or not. This would prevent some receivers from being called improperly, for example in a scenario where one state is called `1.1` and another is called `1.1.2`. Something like:
> 
> ```
> {
>       "type": "TextMessageReceiver",
>       "mediaType": "text/plain",
>       "state": "^3.1.(1|2)?",
>       "stateResolver": "regex"
> }
> ```

Maybe a simple string convention, for instance using the JS RegExp literal: 
```
{
      "type": "TextMessageReceiver",
      "mediaType": "text/plain",
      "state": "/^3.1.(1|2)?/"
}

**Comment by ceifa** [comment]
Good idea! The only problem is if users try to use js regex features on that, like use flags after the last `/`.

**Comment by ceifa** [comment]
Just found the `RegexOptions.ECMAScript`, it can be really useful 🤯

**Comment by ceifa** [comment]
Closing this issue because it's a very low use feature and doesn't have other requests in 3 years
