### ISSUE TITLE
Falha Template Blip Console 

### ISSUE THREAD

**Issue by walldba** [takenet/blip-sdk-csharp#64]
Criei um projeto utilizando `dotnet new blip-console` e estamos utilizando as bibliotecas `Take.Blip.Client` e `Take.Blip.Client.Console` na versão `0.6.10-beta`.

Simulamos um cenário onde a aplicação está rodando e a internet fica indisponível por 1 minuto. Verificamos que após o retorno da conexão, a instância continua rodando, porém o bot fica Offline e não recebe as mensagens enviadas. (Criando uma especie de instância "Zumbi" da aplicação).

Isso é um bug que deve ser corrigido por vocês ou existe algum tratamento que podemos fazer do nosso lado (exceptionHandler ou algo do tipo)?

Obrigado! :)

**Comment by ceifa** [comment]
Apparently it is a problem that only occurs on windows, but not at all.
I will close this issue since we don't have more inputs to solve this.
